### ISSUE TITLE
cluelessbinarytreefinal.elasticbeanstalk.com took too long to respond.

### ISSUE THREAD

**Issue by wtanaka** [kochinting/ClueLessBinaryTree-#1]
was trying to check out your demo page, but got an error, is the site intentionally down?

![screen shot 2017-04-11 at 9 18 19 am](https://cloud.githubusercontent.com/assets/35872/24926588/d1863df8-1e97-11e7-83ef-fe74129cc0db.png)

**Comment by kochinting** [comment]
Thanks for the interest, the site is not maintained anymore. I revised to a youtube demo video link which presented by other team member back to Dec 2015.
